# Auto-generated NixOS configuration for ${hostname}
# Generated by Terraform on ${timestamp()}

{ config, pkgs, lib, ... }:

{
  imports = [
    ../modules/base.nix
    ../modules/media-server.nix
    ../modules/monitoring.nix
    ../modules/ssh-deployment.nix
    ../hardware/${hardware_type}.nix
  ];

  networking = {
    hostName = "${hostname}";
    
    # Static IP configuration
    interfaces.eth0.ipv4.addresses = [{
      address = "${ip_address}";
      prefixLength = 24;
    }];
    defaultGateway = "192.168.1.1";
    nameservers = [ "1.1.1.1" "8.8.8.8" ];
  };

  # SSH deployment configuration
  cistern.ssh = {
    enable = true;
    enablePasswordAuth = true;
    authorizedKeys = [
      "${ssh_public_key}"
    ];
  };

%{ if is_primary }
  # Primary server configuration
  cistern.auth = {
    enable = true;
    method = "basic";
    users = {
      # Admin user will be auto-generated with secure password if not specified
      # To set a custom password, use: htpasswd -nB admin
      %{ if admin_password_hash != "" }
      "admin" = "${admin_password_hash}";
      %{ else }
      # No admin password specified - will be auto-generated on first boot
      %{ endif }
    };
  };

  # Enable SSL for primary server
  cistern.ssl = {
    enable = true;
    domain = "${hostname}.local";
    selfSigned = true;
  };
%{ else }
  # Secondary server - minimal configuration
  cistern.auth.enable = false;
  cistern.ssl.enable = false;
%{ endif }

  # Managed by Terraform - do not edit manually
  system.stateVersion = "24.05";
}